---
title: "Report: Edits Log"
output: html_document
params:
  fileName: NA
  editLog: NA
  editDF: NA
---


```{r,echo=FALSE}
if(is.null(params$fileName)){
  fname <- "DemoData.rwl"
}

if(!is.null(params$fileName)){
  fname <- params$fileName
  }

```

### File: `r fname`

### Log
```{r} 
params$editLog
```

### R Code
```{r, echo=TRUE} 
res <- list()
for(i in 1:nrow(params$editDF)){
  
  if(params$editDF$action[i] == "delete.ring"){
    res[i] <- paste("dat$",
                    params$editDF$series[i],
                    " <- delete.ring(rw.vec = dat$",
                    params$editDF$series[i], 
                    ", rw.vec.yrs = time(dat), year = ",
                    params$editDF$year[i],
                    ", fix.last=",
                    params$editDF$fixLast[i],
                    ")", sep="")
  }
  if(params$editDF$action[i] == "insert.ring"){
    res[i] <- paste("dat$",
                    params$editDF$series[i],
                    " <- insert.ring(rw.vec = dat$",
                    params$editDF$series[i], 
                    ", rw.vec.yrs = time(dat), year = ",
                    params$editDF$year[i],
                    ", ring.value=",
                    params$editDF$value[i],
                    ", fix.last=",
                    params$editDF$fixLast[i],
                    ")", sep="")
  }
}
```

```
library(dplR)
dat <- read.rwl("`r fname`")
```
```{r} 
res
```
