---
title: "Report: Individual Series Correlations"
output: html_document
params:
  fileName: NA
  rwlObject: NA
  cssParams: NA
---

```{r,echo=FALSE}
library(DT)
library(knitr)
library(kableExtra)
cssParams <- params$cssParams
```

```{r,echo=FALSE}
if(is.null(params$fileName)){
  fname <- "DemoData.rwl"
}

if(!is.null(params$fileName)){
  fname <- params$fileName
  }

if(cssParams$datingNotes == ""){
  cssParams$datingNotes <- "No dating notes entered."
}

```

### Date: `r Sys.Date()`

### File: `r fname`

#### Selected Series: 

**`r cssParams$series`**

#### Remaining Series in Master:

```{r,echo=FALSE}
dat <- params$rwlObject
mask <- names(dat) %in% cssParams$series
dat <- dat[,!mask]
nSeries <- ncol(dat)
i <- 4
j <- round(nSeries/i + 0.5)
tmp <- c(names(dat),rep(NA,i * j - nSeries))
res <- matrix(tmp,nrow = j, ncol = i)
#res <- data.frame(res)
res[is.na(res)] <- ""
res2 <- kable(res, format="html") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
gsub("<thead>.*</thead>", "", res2)
```

#### Arguments:

```{r,echo=FALSE}
tab2 <- data.frame(Parameter=c("seg.length","bin.floor","n",
                               "prewhiten","pcrit","biweight",
                               "method",
                               "lag.max"),
                   Value=c(cssParams$seg.length,cssParams$bin.floor,
                           cssParams$n, cssParams$prewhiten, 
                           cssParams$pcrit, cssParams$biweight,
                           cssParams$method,
                           cssParams$lagCCF))
kable(tab2) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```


```{r, echo=FALSE, fig.width=10, fig.height=8}
dat <- params$rwlObject
if(cssParams$n=="NULL"){
  n <- NULL
}
if(cssParams$n!="NULL"){
  n <- as.numeric(cssParams$n)
}
css <- corr.series.seg(dat, series = cssParams$series, 
                       seg.length = cssParams$seg.length, 
                       bin.floor = as.numeric(cssParams$bin.floor),n = n,
                       prewhiten = cssParams$prewhiten, pcrit = cssParams$pcrit,
                       biweight = cssParams$biweight, method = cssParams$method,
                       make.plot=TRUE)
```


```{r, echo=FALSE, fig.width=10, fig.height=8}
yrs <- time(dat)
ccfObject <- ccf.series.rwl(dat[yrs %in% cssParams$winCCF,], 
                            series = cssParams$series, 
                            seg.length = cssParams$seg.length, 
                            bin.floor = as.numeric(cssParams$bin.floor),n = n,
                            prewhiten = cssParams$prewhiten, pcrit = cssParams$pcrit,
                            biweight = cssParams$biweight, method = cssParams$method,
                            lag.max = cssParams$lagCCF,make.plot=TRUE)
```



### Dating Notes
`r cssParams$datingNotes`

### R Code

```
library(dplR)
dat <- read.rwl("`r fname`")
css <- corr.series.seg(dat, series = "`r cssParams$series`", 
                       seg.length = `r cssParams$seg.length`, 
                       bin.floor = `r cssParams$bin.floor`,
                       n = `r cssParams$n`,
                       prewhiten = `r cssParams$prewhiten`, 
                       pcrit = `r cssParams$pcrit`,
                       biweight = `r cssParams$biweight`, 
                       method = "`r cssParams$method`",
                       make.plot=TRUE)
                       
yrs <- time(dat)
win <- `r min(cssParams$winCCF)`:`r max(cssParams$winCCF)`
ccfObject <- ccf.series.rwl(dat[yrs %in% win,], 
                            series = "`r cssParams$series`", 
                            seg.length = `r cssParams$seg.length`, 
                            bin.floor = `r cssParams$bin.floor`,
                            n = `r cssParams$n`,
                            prewhiten = `r cssParams$prewhiten`, 
                            pcrit = `r cssParams$pcrit`,
                            biweight = `r cssParams$biweight`,
                            method = "`r cssParams$method`",
                            lag.max = `r cssParams$lagCCF`,
                            make.plot=TRUE)
           

```
