### (Cross) Correlation between a Series and a Master Chronology
Here you can select a series to investigate in more detail. The plots produced below are from the functions [`corr.series.seg`](https://rdrr.io/cran/dplR/man/corr.series.seg.html), [`ccf.series.rwl`](https://rdrr.io/cran/dplR/man/ccf.series.rwl.html), and [`xskel.ccf.plot`](https://rdrr.io/cran/dplR/man/xskel.ccf.plot.html). As on the previous tab, you can set the detrending options (e.g., `prewhiten`), segment lengths, bin floor and so on. You can also filter out series that you don't want included in the master. E.g., series that might have dating issues that you think will corrupt the master chronology. The selected series is always removed from the master chronology.

You can isolate periods of poor dating using the sliders associated with each plot. Any notes taken will be saved in the generated report. The selected series can be edited and saved in the next tab.

In the first plot ([`corr.series.seg`](https://rdrr.io/cran/dplR/man/corr.series.seg.html)), correlations between the selected series and the master chronology are
shown with horizontal lines according the segment length (with overlapping segments lagged by half the segment length). A centered running correlation with a length equal to the segment length complements the segment correlations. The critical level is shown with a dashed line.

The second plot ([`ccf.series.rwl`](https://rdrr.io/cran/dplR/man/ccf.series.rwl.html))shows cross-correlations between the selected series and the master chronology for each segment. You can change the maximum lag to plot as well as change the time range under consideration.

The third plot ([`xskel.ccf.plot`](https://rdrr.io/cran/dplR/man/xskel.ccf.plot.html)) combines the visual style of crossdating using skeleton plots with the statistical approach of cross-correlation analysis.  In that plot, the top panel shows the normalized values for the master chronology (bottom half) and the selected series (top half) in green. The values are relative. Similarly, the black lines are a skeleton plot for the master and series with the marker years annotated for the master on the bottom axis. The text at the top of the figure gives the correlation between the series and master (green bars) as well as the percentage of agreement between the skeleton bars for the series and master. The bottom panels show cross correlations for the first half (left) and second half of the time series. The user can change the center year for the window as well as its width.
